missing-semester/missing-semester

- _2020/shell-tools.md
> Clarify zsh history search vs. autosuggestions in shell tools lecture

- _2020/security.md
Why? To demonstrate how slightly-differing inputs have widely different outputs, and how repeating the same input generates the same output.
> Provide additional sha1sum examples

- _2020/debugging-profiling.md
Last exercise in Lecture 6 (Version Control); added a code formatter because I couldn't find any typos
> Added prettier as example of a code formatter

- _2020/shell-tools.md
> Fix typo inside shell-tools.md

- _2020/command-line.md
- _2020/data-wrangling.md
- _2020/debugging-profiling.md
- _2020/metaprogramming.md
- _2020/potpourri.md
- _2020/qa.md
- _2020/security.md
- _2020/shell-tools.md
- _2020/version-control.md
Fixed some typos in `_2020/*.md` files.
> Fix small typos

- _2020/command-line.md
Nothing too special, mostly just adding a few words to assist in
sentence flow. I also elaborated a bit more on the tmux prefix to
hopefully make it a bit easier to understand, though it was pretty
self-explanatory to begin with.
Also, this is my first PR! 🙌 🙌 🙌 Thanks to all the instructors
for a great course!
> Small formatting and grammar tweaks

- _2020/shell-tools.md
Added a bunch of clarifying commas and a few missing words/hyphens. Slight clarification between fasd and autojump.
> Minor cleanup

- _2020/version-control.md
This article does a fantastic job of explaining not only what the
conventions are, but _why they are important_. Chris also talks about
other conventions that are significant, like using the imperative
mood in the subject line, and provides delightful and
easy-to-understand examples.
> Add second link for commit message best practices

- index.md
Hello guys, I liked the idea behind that class! So I am started to translate Turkish on the forked clone. This forked repository under in organization named by  [missing-semester-tr](https://github.com/missing-semester-tr). I already translated the main pages like homepage, about page, lecture page. After that, we will continue to translate other pages. 
Thanks for this good resource.
Turkish repo: [github.com/missing-semester-tr/missing-semester-tr.github.io](https://github.com/missing-semester-tr/missing-semester-tr.github.io)
Turkish site: [missing-semester-tr.github.io](https://missing-semester-tr.github.io/)
> Add Turkish translation

- _2020/version-control.md
If I understand this sentence correctly, it means we'll need to fork this project and submit pull request.
> Fix the typo s/clone/fork/ in exercise section in version-control.md.

- _2020/data-wrangling.md
Still a git amateur, unfortunately, so couldn't quite figure out how to make changes to the [former pull request](https://github.com/missing-semester/missing-semester/pull/55). Unless I'm mistaken, this request should contain the changes that @jonhoo and I worked through.
> Search and replace link to Vim lecture, minor R correction and Rust uninstall clarification per Jon review

- _2020/debugging-profiling.md
Practicing pull requests in exercise 7 in Version Control
Tiny grammatical/spelling error, not sure if this was intentional
> Found potential typo in debugging lecture

- index.md
Hii,
I'm translating your course to Portuguese and I would like to include my version on your site.
The translation repo can be found at https://github.com/missing-semester-pt/missing-semester-pt.github.io
Thanks!
> add the Portuguese version

- _2020/data-wrangling.md
> Update data-wrangling.md - period should be comma

- _2020/potpourri.md
Added Azure to the list of popular Cloud providers
> Added Azure to potpourri.md

- _2020/security.md
Obviously there are many other password managers. I added these because they are solid, representative choices. I feel like it is important to list a few more choices here because this is a very practical and important improvement readers can make in their computer security.
> Add pass and 1password as example password managers

- _2020/debugging-profiling.md
Needed in debugging-profiling.md as a dependency of pycallgraph.
> Add instructions to install GraphViz as a prereq

- _2020/debugging-profiling.md
Great work, thanks!
This is just a minor reordering.
> Update debugging-profiling.md: minor reordering

- _2020/editors.md
This has been a useful resource to me.
> Add link to big list of vim-like software

- _2020/command-line.md
Hi!
The "what" in the following sentence from the last exercise in the command line page looks weird to me:
> and figure out what a command to achieve background port forwarding.
I'm no native English speaker though, so I may be wrong :)
Kudos!
> Fix sentence that looks off in last command line exercise

- _2020/version-control.md
Hi, I found two small issues related to format
> add two period mark at Exercises 2 of version-control

- _2020/version-control.md
Hi, I add two punctuation marks for better reading.
> add two punctuation marks

- _2020/command-line.md
Hi! 
I rephrased some parts of the Job control exercise to make it look and sound better.
From:
> Say you don’t want to start a process until another completes, how you would go about it? In this exercise
To:
> Say you don't want to start a process until another completes. How would you go about it? In this exercise,
Thank you for your wonderful lectures by the way.
> Minor rephrasing on Job control Exercise 2

- _2020/course-shell.md
I believe the correct spelling is fanciful. 
Source - Websters Dictionary: https://www.merriam-webster.com/dictionary/fanciful
> Course Overview - changed "fancyful" to "fanciful"

- _2020/security.md
> add missing close parenthesis

- _2019/security.md
- There was a typo on "technical persona" that is corrected.
- Added link to medium profile of @thegrugq
> change _2019/security.md

- _2020/qa.md
Since in the QA video, you both mentioned that using less mouse and more keyboard makes it more efficient.
Using browser to debug and find answer is common in programming.
So I think this is a recommended plugin in this part.
> Add a browser plugin that I found it is useful.

- _2020/command-line.md
I indented the code block as it was breaking the list numbering.
> Fix list numbering

- _2020/version-control.md
Removes an incorrectly used comma that made the sentence it was used in sound clumsy.
> Remove incorrectly used comma

- _2020/command-line.md
Changed sentence in misc to be more readable.
> Modified command-line for readability

- index.md
I started to work on the **Arabic langauge translation** of the website. currently I translated index.md page and part of _2020/version-control.md
please added it so i can gain more support and collaboration to finish all the content.
the repo for the Arabic language is:
https://github.com/missing-semester-ar/missing-semester-ar.github.io
> Added link to Arabic language Translation

- _2020/debugging-profiling.md
This PR contains a few corrections to some typos and an extraneous line.
> Debugging and Profiling corrections

- _2020/course-shell.md
Fixing a small typo/grammatical error
> Fix typo/correct grammar

- index.md
URL: https://missing-semester-bn.github.io/
Github: https://github.com/missing-semester-bn/missing-semester-bn.github.io
> Add link for Bengali translation.

- _2020/editors.md
Some love for non-mac users with a suggestion for a different way to map escape. I would have found this useful, so hopefully others will too!
> add suggestion and link for mapping <ESC>

- _2020/shell-tools.md
The original sentence is a [Garden-path sentence](https://en.wikipedia.org/wiki/Garden-path_sentence) which begins in a way that can lead the reader to think scripts are passed by value.
> Reword confusing sentence in shell-tools.md

- _2019/machine-introspection.md
I think the use of "is" here is a grammatical mistake.
Replacing it with "has".
> Fixed Typo
