missing-semester/missing-semester

_2020/command-line.md

`history 1` returns only the current event, making it look like the only command in history is the script people just pasted into their terminal.
Note that tail prints the last 10 lines by default.

command-line.md/Aliases Exercises: Fix top-10 history script

---

_2020/command-line.md

Following along on macOS, tmux installed via homebrew.
```bash
$ tmux -t test
tmux: illegal option -- t
usage: tmux [-2CluvV] [-c shell-command] [-f file] [-L socket-name]
[-S socket-path] [command [flags]]
```
vs
```bash
$ tmux new -s test # opens tmux session named 'test'
```

tmux -t is illegal option

---

_2020/command-line.md

There is no '-p' option for df, this should probably be 'df -h'.

Fix wrong option in alias example

---

_2020/command-line.md

Second link in Exercises: Terminal multiplexer is a duplicate of the first link.
Currently, both point to https://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/
Did you mean to direct the second link (about customizing your tmux conf) to the sequel blog post from the Ham Vocke at https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/ ?

incorrect link in exercises: terminal multiplexer

---

_2020/command-line.md

linked url: https://www.ssh.com/ssh/agents
correct url: https://www.ssh.com/ssh/agent

link to info about ssh-agent is incorrect

---

_2020/debugging-profiling.md

The current link to cProfile in the exercises links to the python2 documentation. Maybe this should be the python3 documentation instead?

Change link to cProfile from python2 -> python3 docs

---

_2020/debugging-profiling.md

Exercises numbers were incorrect because the code blocks were not indented. This PR indents the code blocks and post-block exercise text so that Markdown interprets the numbered lists correctly. Only the debugging-profiling.md page has been edited.

Debugging-Profiling - fix exercise autonumbers and indenting

---

_2020/command-line.md

`$!` is a special parameter, not an environment variable.
"special parameter" is used in both the Open Group specification:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html
and the bash documentation:
https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html

Describe the shell parameter $! correctly

---

_2020/command-line.md

Fixed a typo in command-lind.md
Specifically, under SSH configuration, changed "You can specify config settings **in** a per user basis." to "You can specify config settings **on** a per user basis."

Typo in command-line.md

---

_2020/data-wrangling.md

Delete a redundant whitespace here, so it will become a closing quotation mark instead of a open one.

fix typo in _2020/data-wrangling.md

---

_2020/version-control.md

fix this typo to make the struct unify and the object name consistent

TYPO in version-control.md

---

_2020/shell-tools.md

Additionally,
https://github.com/missing-semester/missing-semester/blob/47c053d5fcc51fe0b738ded4e190d400a6bd765e/_2020/shell-tools.md#L116 talks about Bash's implementation of `[`/`test`, but then points to the manpage; similar to the discussion in #12, this isn't exactly true as the `[`/`test` being used would be the builtin and not `/usr/bin/test`; the reference for the builtin is `help test`.
https://github.com/missing-semester/missing-semester/blob/47c053d5fcc51fe0b738ded4e190d400a6bd765e/_2020/shell-tools.md#L176 still mentions an "aliasing section", which apparently has been removed.

Add small fixes for shell tools lecture

---

_2020/metaprogramming.md

possibly a bugfix for wrong hyperlink in lecture notes.

Possibly wrong GitHubPages hyperlink.

---

.gitignore
_2020/metaprogramming.md

In the lectures you used some python scripts, it may generate
a __pycache__ folder and submit it to remote.

Add '__pycache__/' to .gitignore

---

_2020/potpourri.md

Sorry, I forgot to add this to the previous PR. I hope it doesn't break whatever Markdown parser you use; should be Commonmark compliant.

Fix TOC entry for hammerspoon

---

index.md

Hi, thank you for the awesome course materials, they are really helpful for us student.
I started the translation of the website into Vietnamese (finished about.md).
The translation repo can be found at https://github.com/missing-semester-vn/missing-semester-vn.github.io
and the Vietnamese website is at https://missing-semester-vn.github.io/
Other Vietnameses, you are welcome to contribute too!

Added Vietnamese translation site link

---

_2020/course-shell.md

I tried adding it to the front page, but then I thought that nobody would read it. Perhaps just before the first set of exercises is a good place for this note.
Fixes #92.

Add note on (lack of) solutions to exercises

---

_2020/data-wrangling.md

I initially re-read the "sum of the difference between the two columns" a few times. Subtracting each row individually across the columns and then summing is equivalent to summing each column and then subtracting, so I figured changing the wording could be useful for others. Let me know if I am misunderstanding the exercise provided.
the sum of the difference between the two columns
-->
the difference of the sum of each column

Update data-wrangling.md -- clarify wording

---

_2020/version-control.md

On the [version control page](https://missing.csail.mit.edu/2020/version-control/) the merging branches diagram looks different than all the others and is hard to read (2nd diagram in image). 
This PR brings it in line with all the other diagrams on the page so now it looks like this:

Fix background style on merging branches diagram

---

_2020/shell-tools.md

Tested in zsh 5.8, fish 3.1.2, bash 3.2.57 and bash 5.1.4.
Since the default behavior keeps space-led commands, I also see value in instead chopping the paragraph. Maybe keep the last line that brings attention to the existence of `.zsh_history` and equivalents. Students can discover such configurations when exploring dotfiles during Lecture 5.
Thanks for putting this succinct and practical course together.

Clarify default shell history behavior

---

_2020/debugging-profiling.md

The official line_profiler repo changed ownership from @rkern to @pyutils. This updates the links in _2020/debugging-profiling.md to the @pyutils repo.

Update line_profiler link

---

index.md

Thank you for this great material! Our team started to translate it into Japanese. I would appreciate it if you could add the link.
Web: https://missing-semester-jp.github.io/
GIthub: https://github.com/missing-semester-jp/missing-semester-jp.github.io
Best,
Yusuke

Add a link to the Japanese translation

---

_2020/metaprogramming.md

Because `plot-data.png` depends on `data.dat` in a pattern rule, here it should also be `data.dat` but not `foot.dat`.

Fix filename in the text to match the example

---

_2020/editors.md

All sections had their corresponding key bindings except this one.

Add visual mode key bindings

---

_2020/course-shell.md

A beginner to shell may be confused by how or why `cat < hello.txt` and
`cat hello.txt` yield the same output, especially in the context of
understanding rewiring of input / output streams.

Clarify how cat functions

---

_2020/version-control.md

Add a plural to the parent variable in the version control lecture. It is more coherent with the surrounding text always using plural.

Add plural to parent variable

---

_2020/version-control.md

There is no explanation for how to add aliases to the git config
given in the course, so having a link to gits documentation might
help guide students.
This commit is done as a part of [exercise 7][1].
[1]: https://missing.csail.mit.edu/2020/version-control/#exercises

Add link to Git alias section in exercise

---

_2020/debugging-profiling.md

Adding a link to [strace zine](https://jvns.ca/strace-zine-unfolded.pdf) from [jvns](https://jvns.ca/)' blog.
She has some interesting [resources](https://jvns.ca/categories/strace/) on practical strace usage, so I thought it might be a good pointer for readers.

Add a really nice strace zine resource

---

_2020/data-wrangling.md

As of spring 2020, the command-line option --slave is deprecated.
(https://github.com/wch/r-source/blob/trunk/src/main/CommandLineArgs.c#L156-L158)
Using --no-echo would make R run as quietly as possible, and be
understandable to programming students. (https://www.mankier.com/1/R)

Use --no-echo for R option

---

_2020/command-line.md

According to `man ssh`. On macOS, if public key path is specified, user would come across `Permissions 0644 for '/Users/username/.ssh/id_ed25519.pub' are too open`.

Private key path is expected after -i of ssh client

---

README.md

'content' should be plural and verb adjusted accordingly

FIX: Spelling mistakes

---

static/css/main.css

Added CSS rule to print the URL after an external link in print view.
This might come in handy as some people still like to print out their stuff.

Feature: Show URL after Links in Print View

---

_2020/shell-tools.md

In file `_2020/shell-tools.md`, a `\` should be added to the front of `!` inside `""`.

Fix a wrong usage of ! within double quotation marks

---

_2020/shell-tools.md

I found that the history of zsh on my Mac is `zsh_history`, not `zhistory`.

change `.zhistory` to `.zsh_history`

---

static/css/main.css

When printing as pdf some of the text inside pre tags was not visible due to overflow. This solves that, by making the text wrap inside pre tags when printing.

Text inside pre is visible while printing as pdf.

---

_2019/editors.md

Just doing my git exercises, thanks for the lectures by the way

Fix typo on 2019 editors page

---

_2020/command-line.md

Fixing a typo as a part of an exercise. Thank you for this great course :)

Fix typo (`locahost` to `localhost`)

---

_2020/editors.md

Hi, I updated the link to the Vim binding for Jupyter Notebook because the old link points to an archived repository. 
The new link points to an extension that works for both Jupyter Notebook and Jupyter Lab.

Update Vim binding for Jupyter

---

_2020/metaprogramming.md

Small typo found [here](https://missing.csail.mit.edu/2020/metaprogramming/#:~:text=for%20Ruby%20libraries%2C-,PyPi,-for%20Python%20libraries).

PyPi → PyPI (Python Package Index)

---

_2020/debugging-profiling.md

The original link to pycallgraph in the Debugging exercise is outdated, and `pip install pycallgraph` is no longer functional. The project is now actively maintained at https://github.com/Lewiscowles1986/py-call-graph, so I've updated the link to point to the documentation page of the new repository.

Update python call graph link

---

_2020/version-control.md

This PR clarifies the documentation around configuring a global .gitignore file using `git config --global core.excludesfile`. The previous wording may have implied that the file is created automatically by the command. The updated text makes it explicit that the file must be manually created and populated with ignore patterns.
[Reference](https://stackoverflow.com/questions/7335420/global-git-ignore#:~:text=Important%3A%20The%20above%20commands%20will%20only%20set%20the%20location%20of%20the%20ignore%20file%20that%20git%20will%20use.%20The%20file%20has%20to%20still%20be%20manually%20created%20in%20that%20location%20and%20populated%20with%20the%20ignore%20list.%20(from%20muruge%27s%20comment))

Clarify global gitignore file must be manually created

---

_2020/command-line.md

The `-o` flag is useless for latest version of `ssh-keygen` as it uses the new new private key format by default.
See details at: https://stackoverflow.com/questions/70292969

Remove unnecessary flags for ssh-keygen

---

_2020/version-control.md

The current description of `git checkout <revision>` states it "updates HEAD and current branch", but this is only true when checking out a branch. When checking out a specific commit hash or tag, Git enters detached HEAD state and no branch is updated.
This change clarifies the behaviour.

Fix misleading description of git checkout command

---

_2020/shell-tools.md

Replaced the broken `find … convert {} {}.jpg` example.
Added two working commands
Switched from the deprecated convert binary to ImageMagick 7’s magick front-end.
The previous example generated file.png.jpg.
Using magick avoids the name clash with macOS’ /usr/bin/convert and reflects current ImageMagick practice.

find: give working PNG→JPG examples for both GNU and BSD find
